package com.bdy.model;

// Generated 2014/4/17 �U�� 08:38:49 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * BdyBill generated by hbm2java
 */
public class BdyBill implements java.io.Serializable {

	private int billId;
	private BdyDiscount bdyDiscount;
	private BdyOrder bdyOrder;
	private BdyEmp bdyEmp;
	private Date endDate;
	private Double price;
	private Integer custNum;

	public BdyBill() {
	}

	public BdyBill(int billId) {
		this.billId = billId;
	}

	public BdyBill(int billId, BdyDiscount bdyDiscount, BdyOrder bdyOrder,
			BdyEmp bdyEmp, Date endDate, Double price, Integer custNum) {
		this.billId = billId;
		this.bdyDiscount = bdyDiscount;
		this.bdyOrder = bdyOrder;
		this.bdyEmp = bdyEmp;
		this.endDate = endDate;
		this.price = price;
		this.custNum = custNum;
	}

	public int getBillId() {
		return this.billId;
	}

	public void setBillId(int billId) {
		this.billId = billId;
	}

	public BdyDiscount getBdyDiscount() {
		return this.bdyDiscount;
	}

	public void setBdyDiscount(BdyDiscount bdyDiscount) {
		this.bdyDiscount = bdyDiscount;
	}

	public BdyOrder getBdyOrder() {
		return this.bdyOrder;
	}

	public void setBdyOrder(BdyOrder bdyOrder) {
		this.bdyOrder = bdyOrder;
	}

	public BdyEmp getBdyEmp() {
		return this.bdyEmp;
	}

	public void setBdyEmp(BdyEmp bdyEmp) {
		this.bdyEmp = bdyEmp;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getCustNum() {
		return this.custNum;
	}

	public void setCustNum(Integer custNum) {
		this.custNum = custNum;
	}

}
