package com.bdy.model;

// Generated 2014/5/15 �U�� 02:50:35 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BdyBill generated by hbm2java
 */
public class BdyBill implements java.io.Serializable {

	private int billId;
	private BdyDiscount bdyDiscount;
	private BdyEmp bdyEmp;
	private Date endDate;
	private Integer custNum;
	private Double price;
	private Double finPrice;
	private Set bdyBilldetails = new HashSet(0);

	public BdyBill() {
	}

	public BdyBill(int billId) {
		this.billId = billId;
	}

	public BdyBill(int billId, BdyDiscount bdyDiscount, BdyEmp bdyEmp,
			Date endDate, Integer custNum, Double price, Double finPrice,
			Set bdyBilldetails) {
		this.billId = billId;
		this.bdyDiscount = bdyDiscount;
		this.bdyEmp = bdyEmp;
		this.endDate = endDate;
		this.custNum = custNum;
		this.price = price;
		this.finPrice = finPrice;
		this.bdyBilldetails = bdyBilldetails;
	}

	public int getBillId() {
		return this.billId;
	}

	public void setBillId(int billId) {
		this.billId = billId;
	}

	public BdyDiscount getBdyDiscount() {
		return this.bdyDiscount;
	}

	public void setBdyDiscount(BdyDiscount bdyDiscount) {
		this.bdyDiscount = bdyDiscount;
	}

	public BdyEmp getBdyEmp() {
		return this.bdyEmp;
	}

	public void setBdyEmp(BdyEmp bdyEmp) {
		this.bdyEmp = bdyEmp;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getCustNum() {
		return this.custNum;
	}

	public void setCustNum(Integer custNum) {
		this.custNum = custNum;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getFinPrice() {
		return this.finPrice;
	}

	public void setFinPrice(Double finPrice) {
		this.finPrice = finPrice;
	}

	public Set getBdyBilldetails() {
		return this.bdyBilldetails;
	}

	public void setBdyBilldetails(Set bdyBilldetails) {
		this.bdyBilldetails = bdyBilldetails;
	}

}
