package com.bdy.model;

// Generated 2014/5/15 �U�� 02:50:35 by Hibernate Tools 4.0.0

/**
 * BdyBilldetail generated by hbm2java
 */
public class BdyBilldetail implements java.io.Serializable {

	private int bdId;
	private BdyOrder bdyOrder;
	private BdyBill bdyBill;

	public BdyBilldetail() {
	}

	public BdyBilldetail(int bdId) {
		this.bdId = bdId;
	}

	public BdyBilldetail(int bdId, BdyOrder bdyOrder, BdyBill bdyBill) {
		this.bdId = bdId;
		this.bdyOrder = bdyOrder;
		this.bdyBill = bdyBill;
	}

	public int getBdId() {
		return this.bdId;
	}

	public void setBdId(int bdId) {
		this.bdId = bdId;
	}

	public BdyOrder getBdyOrder() {
		return this.bdyOrder;
	}

	public void setBdyOrder(BdyOrder bdyOrder) {
		this.bdyOrder = bdyOrder;
	}

	public BdyBill getBdyBill() {
		return this.bdyBill;
	}

	public void setBdyBill(BdyBill bdyBill) {
		this.bdyBill = bdyBill;
	}

}
