package com.bdy.model;

// Generated 2014/5/28 �U�� 02:06:32 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BdyBillHistory generated by hbm2java
 */
public class BdyBillHistory implements java.io.Serializable {

	private int billId;
	private Date endDate;
	private Integer custNum;
	private String disName;
	private String billEmpId;
	private String billEmpName;
	private Double price;
	private Double finPrice;
	private String discription;
	private Set bdyOrderlistReports = new HashSet(0);

	public BdyBillHistory() {
	}

	public BdyBillHistory(int billId) {
		this.billId = billId;
	}

	public BdyBillHistory(int billId, Date endDate, Integer custNum,
			String disName, String billEmpId, String billEmpName, Double price,
			Double finPrice, String discription, Set bdyOrderlistReports) {
		this.billId = billId;
		this.endDate = endDate;
		this.custNum = custNum;
		this.disName = disName;
		this.billEmpId = billEmpId;
		this.billEmpName = billEmpName;
		this.price = price;
		this.finPrice = finPrice;
		this.discription = discription;
		this.bdyOrderlistReports = bdyOrderlistReports;
	}

	public int getBillId() {
		return this.billId;
	}

	public void setBillId(int billId) {
		this.billId = billId;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getCustNum() {
		return this.custNum;
	}

	public void setCustNum(Integer custNum) {
		this.custNum = custNum;
	}

	public String getDisName() {
		return this.disName;
	}

	public void setDisName(String disName) {
		this.disName = disName;
	}

	public String getBillEmpId() {
		return this.billEmpId;
	}

	public void setBillEmpId(String billEmpId) {
		this.billEmpId = billEmpId;
	}

	public String getBillEmpName() {
		return this.billEmpName;
	}

	public void setBillEmpName(String billEmpName) {
		this.billEmpName = billEmpName;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getFinPrice() {
		return this.finPrice;
	}

	public void setFinPrice(Double finPrice) {
		this.finPrice = finPrice;
	}

	public String getDiscription() {
		return this.discription;
	}

	public void setDiscription(String discription) {
		this.discription = discription;
	}

	public Set getBdyOrderlistReports() {
		return this.bdyOrderlistReports;
	}

	public void setBdyOrderlistReports(Set bdyOrderlistReports) {
		this.bdyOrderlistReports = bdyOrderlistReports;
	}

}
