package com.bdy.model;

// Generated 2014/4/17 �U�� 08:38:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BdyDiscount generated by hbm2java
 */
public class BdyDiscount implements java.io.Serializable {

	private int disId;
	private String name;
	private Double disPrice;
	private Set bdyBills = new HashSet(0);

	public BdyDiscount() {
	}

	public BdyDiscount(int disId) {
		this.disId = disId;
	}

	public BdyDiscount(int disId, String name, Double disPrice, Set bdyBills) {
		this.disId = disId;
		this.name = name;
		this.disPrice = disPrice;
		this.bdyBills = bdyBills;
	}

	public int getDisId() {
		return this.disId;
	}

	public void setDisId(int disId) {
		this.disId = disId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getDisPrice() {
		return this.disPrice;
	}

	public void setDisPrice(Double disPrice) {
		this.disPrice = disPrice;
	}

	public Set getBdyBills() {
		return this.bdyBills;
	}

	public void setBdyBills(Set bdyBills) {
		this.bdyBills = bdyBills;
	}

}
