package com.bdy.model;

// Generated 2014/5/15 �U�� 02:50:35 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BdyEmp generated by hbm2java
 */
public class BdyEmp implements java.io.Serializable {

	private String empId;//
	private BdyPriority bdyPriority;//
	private String passwd;//
	private String name;//
	private Character sex;
	private Date comedate;//
	private Integer salary;//
	private String phone;//
	private String empAddress;
	private Integer resign;//
	private Set bdyOrders = new HashSet(0);
	private Set bdyBills = new HashSet(0);

	public BdyEmp() {
	}

	public BdyEmp(String empId) {
		super();
		this.empId = empId;
	}

	public BdyEmp(String empId, String passwd) {
		this.empId = empId;
		this.passwd = passwd;
	}

	public BdyEmp(String empId, BdyPriority bdyPriority, String passwd,
			String name, Character sex, Date comedate, Integer salary,
			String phone, String empAddress, Integer resign, Set bdyOrders,
			Set bdyBills) {
		this.empId = empId;
		this.bdyPriority = bdyPriority;
		this.passwd = passwd;
		this.name = name;
		this.sex = sex;
		this.comedate = comedate;
		this.salary = salary;
		this.phone = phone;
		this.empAddress = empAddress;
		this.resign = resign;
		this.bdyOrders = bdyOrders;
		this.bdyBills = bdyBills;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public BdyPriority getBdyPriority() {
		return this.bdyPriority;
	}

	public void setBdyPriority(BdyPriority bdyPriority) {
		this.bdyPriority = bdyPriority;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	public Date getComedate() {
		return this.comedate;
	}

	public void setComedate(Date comedate) {
		this.comedate = comedate;
	}

	public Integer getSalary() {
		return this.salary;
	}

	public void setSalary(Integer salary) {
		this.salary = salary;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmpAddress() {
		return this.empAddress;
	}

	public void setEmpAddress(String empAddress) {
		this.empAddress = empAddress;
	}

	public Integer getResign() {
		return this.resign;
	}

	public void setResign(Integer resign) {
		this.resign = resign;
	}

	public Set getBdyOrders() {
		return this.bdyOrders;
	}

	public void setBdyOrders(Set bdyOrders) {
		this.bdyOrders = bdyOrders;
	}

	public Set getBdyBills() {
		return this.bdyBills;
	}

	public void setBdyBills(Set bdyBills) {
		this.bdyBills = bdyBills;
	}

}
