package com.bdy.model;

// Generated 2014/4/16 �U�� 04:39:32 by Hibernate Tools 4.0.0

/**
 * BdyBill generated by hbm2java
 */
public class BdyFloor implements java.io.Serializable {

	private int floorid;
	private String name;
	
	public int getFloorid() {
		return floorid;
	}
	public void setFloorid(int id) {
		this.floorid = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	public BdyFloor() {
	}
}
