package com.bdy.model;

// Generated 2014/4/17 �U�� 08:38:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BdyFood generated by hbm2java
 */
public class BdyFood implements java.io.Serializable {

	private int fdId;
	private BdyFoodkind bdyFoodkind;
	private String name;
	private Double price;
	private Integer qty;
	private String descript;
	private Set bdyOrderlists = new HashSet(0);

	public BdyFood() {
	}

	public BdyFood(int fdId) {
		this.fdId = fdId;
	}

	public BdyFood(int fdId, BdyFoodkind bdyFoodkind, String name,
			Double price, Integer qty, String descript, Set bdyOrderlists) {
		this.fdId = fdId;
		this.bdyFoodkind = bdyFoodkind;
		this.name = name;
		this.price = price;
		this.qty = qty;
		this.descript = descript;
		this.bdyOrderlists = bdyOrderlists;
	}

	public int getFdId() {
		return this.fdId;
	}

	public void setFdId(int fdId) {
		this.fdId = fdId;
	}

	public BdyFoodkind getBdyFoodkind() {
		return this.bdyFoodkind;
	}

	public void setBdyFoodkind(BdyFoodkind bdyFoodkind) {
		this.bdyFoodkind = bdyFoodkind;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	public Set getBdyOrderlists() {
		return this.bdyOrderlists;
	}

	public void setBdyOrderlists(Set bdyOrderlists) {
		this.bdyOrderlists = bdyOrderlists;
	}

}
