package com.bdy.model;

// Generated 2014/4/17 �U�� 08:38:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BdyFoodkind generated by hbm2java
 */
public class BdyFoodkind implements java.io.Serializable {

	private int fkId;
	private BdyMakearea bdyMakearea;
	private String name;
	private Double period;
	private Set bdyOrderlists = new HashSet(0);
	private Set bdyFoods = new HashSet(0);
	private Set bdySetdetails = new HashSet(0);
	private int isMain;
	private int seq;
	
	public int getSeq() {
		return seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}
	public int getIsMain() {
		return isMain;
	}

	public void setIsMain(int isMain) {
		this.isMain = isMain;
	}

	public BdyFoodkind() {
	}

	public BdyFoodkind(int fkId) {
		this.fkId = fkId;
	}

	public BdyFoodkind(int fkId, BdyMakearea bdyMakearea, String name,
			Double period, Set bdyOrderlists, Set bdyFoods, Set bdySetdetails) {
		this.fkId = fkId;
		this.bdyMakearea = bdyMakearea;
		this.name = name;
		this.period = period;
		this.bdyOrderlists = bdyOrderlists;
		this.bdyFoods = bdyFoods;
		this.bdySetdetails = bdySetdetails;
	}

	public int getFkId() {
		return this.fkId;
	}

	public void setFkId(int fkId) {
		this.fkId = fkId;
	}

	public BdyMakearea getBdyMakearea() {
		return this.bdyMakearea;
	}

	public void setBdyMakearea(BdyMakearea bdyMakearea) {
		this.bdyMakearea = bdyMakearea;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPeriod() {
		return this.period;
	}

	public void setPeriod(Double period) {
		this.period = period;
	}

	public Set getBdyOrderlists() {
		return this.bdyOrderlists;
	}

	public void setBdyOrderlists(Set bdyOrderlists) {
		this.bdyOrderlists = bdyOrderlists;
	}

	public Set getBdyFoods() {
		return this.bdyFoods;
	}

	public void setBdyFoods(Set bdyFoods) {
		this.bdyFoods = bdyFoods;
	}

	public Set getBdySetdetails() {
		return this.bdySetdetails;
	}

	public void setBdySetdetails(Set bdySetdetails) {
		this.bdySetdetails = bdySetdetails;
	}

}
