package com.bdy.model;

// Generated 2014/5/8 �U�� 04:44:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BdyMainkind generated by hbm2java
 */
public class BdyMainkind implements java.io.Serializable {

	private int mkId;
	private String name;
	private Set bdyFoods = new HashSet(0);

	public BdyMainkind() {
	}

	public BdyMainkind(int mkId) {
		this.mkId = mkId;
	}

	public BdyMainkind(int mkId, String name, Set bdyFoods) {
		this.mkId = mkId;
		this.name = name;
		this.bdyFoods = bdyFoods;
	}

	public int getMkId() {
		return this.mkId;
	}

	public void setMkId(int mkId) {
		this.mkId = mkId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getBdyFoods() {
		return this.bdyFoods;
	}

	public void setBdyFoods(Set bdyFoods) {
		this.bdyFoods = bdyFoods;
	}

}
