package com.bdy.model;

// Generated 2014/4/17 �U�� 08:38:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BdyMakearea generated by hbm2java
 */
public class BdyMakearea implements java.io.Serializable {

	private int maId;
	private String name;
	private Set bdyFoodkinds = new HashSet(0);

	public BdyMakearea() {
	}

	public BdyMakearea(int maId) {
		this.maId = maId;
	}

	public BdyMakearea(int maId, String name, Set bdyFoodkinds) {
		this.maId = maId;
		this.name = name;
		this.bdyFoodkinds = bdyFoodkinds;
	}

	public int getMaId() {
		return this.maId;
	}

	public void setMaId(int maId) {
		this.maId = maId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getBdyFoodkinds() {
		return this.bdyFoodkinds;
	}

	public void setBdyFoodkinds(Set bdyFoodkinds) {
		this.bdyFoodkinds = bdyFoodkinds;
	}

}
