package com.bdy.model;

// Generated 2014/5/15 �U�� 05:00:03 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;

/**
 * BdyNews generated by hbm2java
 */
public class BdyNews implements java.io.Serializable {

	private int newsId;
	private Serializable newsTittle;
	private Serializable newsContent;
	private Date newsPostdate;
	private String newsPostid;

	public BdyNews() {
	}

	public BdyNews(int newsId) {
		this.newsId = newsId;
	}

	public BdyNews(int newsId, Serializable newsTittle,
			Serializable newsContent, Date newsPostdate, String newsPostid) {
		this.newsId = newsId;
		this.newsTittle = newsTittle;
		this.newsContent = newsContent;
		this.newsPostdate = newsPostdate;
		this.newsPostid = newsPostid;
	}

	public int getNewsId() {
		return this.newsId;
	}

	public void setNewsId(int newsId) {
		this.newsId = newsId;
	}

	public Serializable getNewsTittle() {
		return this.newsTittle;
	}

	public void setNewsTittle(Serializable newsTittle) {
		this.newsTittle = newsTittle;
	}

	public Serializable getNewsContent() {
		return this.newsContent;
	}

	public void setNewsContent(Serializable newsContent) {
		this.newsContent = newsContent;
	}

	public Date getNewsPostdate() {
		return this.newsPostdate;
	}

	public void setNewsPostdate(Date newsPostdate) {
		this.newsPostdate = newsPostdate;
	}

	public String getNewsPostid() {
		return this.newsPostid;
	}

	public void setNewsPostid(String newsPostid) {
		this.newsPostid = newsPostid;
	}

}
