package com.bdy.model;

// Generated 2014/4/17 �U�� 08:38:49 by Hibernate Tools 4.0.0

/**
 * BdyOrderlist generated by hbm2java
 */
public class BdyOrderlist implements java.io.Serializable {

	private int odlistId;
	private BdyOrder bdyOrder;
	private BdySet bdySet;
	private BdyFood bdyFood;
	private BdyFoodkind bdyFoodkind;
	private Double addmoney;
	private Integer olState;

	public BdyOrderlist() {
	}

	public BdyOrderlist(int odlistId) {
		this.odlistId = odlistId;
	}

	public BdyOrderlist(int odlistId, BdyOrder bdyOrder, BdySet bdySet,
			BdyFood bdyFood, BdyFoodkind bdyFoodkind, Double addmoney,
			Integer olState) {
		this.odlistId = odlistId;
		this.bdyOrder = bdyOrder;
		this.bdySet = bdySet;
		this.bdyFood = bdyFood;
		this.bdyFoodkind = bdyFoodkind;
		this.addmoney = addmoney;
		this.olState = olState;
	}

	public int getOdlistId() {
		return this.odlistId;
	}

	public void setOdlistId(int odlistId) {
		this.odlistId = odlistId;
	}

	public BdyOrder getBdyOrder() {
		return this.bdyOrder;
	}

	public void setBdyOrder(BdyOrder bdyOrder) {
		this.bdyOrder = bdyOrder;
	}

	public BdySet getBdySet() {
		return this.bdySet;
	}

	public void setBdySet(BdySet bdySet) {
		this.bdySet = bdySet;
	}

	public BdyFood getBdyFood() {
		return this.bdyFood;
	}

	public void setBdyFood(BdyFood bdyFood) {
		this.bdyFood = bdyFood;
	}

	public BdyFoodkind getBdyFoodkind() {
		return this.bdyFoodkind;
	}

	public void setBdyFoodkind(BdyFoodkind bdyFoodkind) {
		this.bdyFoodkind = bdyFoodkind;
	}

	public Double getAddmoney() {
		return this.addmoney;
	}

	public void setAddmoney(Double addmoney) {
		this.addmoney = addmoney;
	}

	public Integer getOlState() {
		return this.olState;
	}

	public void setOlState(Integer olState) {
		this.olState = olState;
	}

}
