package com.bdy.model;

// Generated 2014/4/17 �U�� 08:38:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BdyPriority generated by hbm2java
 */
public class BdyPriority implements java.io.Serializable {

	private int priId;
	private String jobname;
	private Integer prio;
	private Set bdyEmps = new HashSet(0);

	public BdyPriority() {
	}

	public BdyPriority(int priId) {
		this.priId = priId;
	}

	public BdyPriority(int priId, String jobname, Integer prio, Set bdyEmps) {
		this.priId = priId;
		this.jobname = jobname;
		this.prio = prio;
		this.bdyEmps = bdyEmps;
	}

	public int getPriId() {
		return this.priId;
	}

	public void setPriId(int priId) {
		this.priId = priId;
	}

	public String getJobname() {
		return this.jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}

	public Integer getPrio() {
		return this.prio;
	}

	public void setPrio(Integer prio) {
		this.prio = prio;
	}

	public Set getBdyEmps() {
		return this.bdyEmps;
	}

	public void setBdyEmps(Set bdyEmps) {
		this.bdyEmps = bdyEmps;
	}

}
