package com.bdy.model;

// Generated 2014/4/17 �U�� 08:38:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BdySet generated by hbm2java
 */
public class BdySet implements java.io.Serializable {

	private int setId;
	private String name;
	private Double price;
	private Set bdyOrderlists = new HashSet(0);
	private Set bdySetdetails = new HashSet(0);

	public BdySet() {
	}

	public BdySet(int setId) {
		this.setId = setId;
	}

	public BdySet(int setId, String name, Double price, Set bdyOrderlists,
			Set bdySetdetails) {
		this.setId = setId;
		this.name = name;
		this.price = price;
		this.bdyOrderlists = bdyOrderlists;
		this.bdySetdetails = bdySetdetails;
	}

	public int getSetId() {
		return this.setId;
	}

	public void setSetId(int setId) {
		this.setId = setId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Set getBdyOrderlists() {
		return this.bdyOrderlists;
	}

	public void setBdyOrderlists(Set bdyOrderlists) {
		this.bdyOrderlists = bdyOrderlists;
	}

	public Set getBdySetdetails() {
		return this.bdySetdetails;
	}

	public void setBdySetdetails(Set bdySetdetails) {
		this.bdySetdetails = bdySetdetails;
	}

}
